
load('\\172.23.254.106\Data25\HNCT\icEEG Analysis\Analysis\EEG_behavior\normal_pipeline_file_info\normal_pipeline_file_info_21_04_22.mat')
for i = 1 : 31
    try
        copyfile(['\\172.23.254.106\Data25\HNCT\icEEG Analysis\Analysis\EEG_behavior\', patients{i},...
            '\icEEG\HNCT Auditory ID Combined\meanpower_traces_157bins_zscore_recentered_rejoutliers',...
            mean_suffixes_157bins_100ms_filter_baseline5to0_common_b{i},'.mat'],...
            ['\\172.23.254.106\Data25\HNCT\icEEG Analysis\Analysis\EEG_behavior\HNCT ERP movies\',...
            patients{i}, '\meanpower_traces_157bins_zscore_recentered_rejoutliers',...
            mean_suffixes_157bins_100ms_filter_baseline5to0_common_b{i},'.mat'])
        i
    catch
        copyfile(['\\172.23.254.106\Data25\HNCT\icEEG Analysis\Analysis\EEG_behavior\', patients{i},...
            '\icEEG\HNCT Auditory ID Combined\meanpower_traces_156bins_zscore_recentered_rejoutliers',...
            mean_suffixes_157bins_100ms_filter_baseline5to0_common_b{i},'.mat'],...
            ['\\172.23.254.106\Data25\HNCT\icEEG Analysis\Analysis\EEG_behavior\HNCT ERP movies\',...
            patients{i}, '\meanpower_traces_156bins_zscore_recentered_rejoutliers',...
            mean_suffixes_157bins_100ms_filter_baseline5to0_common_b{i},'.mat'])
        i
    end
end

